### ISSUE TITLE
Add more helpers

### ISSUE THREAD

**Issue by oskarrough** [oskarrough/ember-date-fns#1]
Currently only the `format` method has a helper. Let's make more!

Which naming convention should we use? For instance, here's the `isToday` function and some possible solutions?

```
date-is-today
date-fns-is-today
ember-date-fns-is-today
```

could be tedious to write date-fns instead of just date. buuuut date is probably too common.

**Comment by n1ru4l** [comment]
I would prefer `date-fns-is-today`.

Also a nice feature would be something like: https://github.com/DockYard/ember-composable-helpers#configuration. So you can choose which helpers you really want to have in your app.
