### ISSUE TITLE
Does not work with ember-cli 3.5.0-beta.2

### ISSUE THREAD

**Issue by RobbieTheWagner** [oskarrough/ember-date-fns#14]
I'm hitting this error:

`ENOENT: no such file or directory, open '/var/folders/tf/h_tyhd41165d978ps4hgc5wc0000gn/T/broccoli-67565lS9lkUhGsKi/out-453-broccoli_debug_debug_5_vendor_js/vendor/-ember-date-fns-bundle.js'`

I believe this is because ember-cli now tries to use your system's `temp` folder, rather than creating a `tmp` folder.

**Comment by oskarrough** [comment]
Hum, not sure what to do about that. Thank you for reporting.

@btecu any ideas? :)

It's probably something here https://github.com/oskarrough/ember-date-fns/blob/master/lib/webpack-dependency-plugin.js. I'm wondering if we could replace the custom webpack stuff with https://github.com/ef4/ember-auto-import.

**Comment by RobbieTheWagner** [comment]
@oskarrough I think we definitely want to make sure we get tree shaking, which I think is probably why Webpack was used? I think probably the Webpack stuff needs to be configured to use default temp folders, rather than generated `tmp`.

**Comment by btecu** [comment]
@oskarrough I haven't tested `ember-cli` `3.5.0-beta.2` yet. I only know it comes with the new `Broccoli 2` so it's probably related.

**Comment by robclancy** [comment]
3.5 is released and this still doesn't work...

**Comment by amk221** [comment]
Also getting this with Ember CLI 3.5

**Comment by RobbieTheWagner** [comment]
Yeah, this isn't going to work without changes. We need to not use Webpack and rely on built in ember-cli behavior here, I believe. I ended up importing with ember-auto-import rather than using this addon.

**Comment by robclancy** [comment]
Yeah I've already removed this, imported the library with ember-auto-import and made any helper I needed myself.

**Comment by oskarrough** [comment]
@robclancy yea, same here. And the two (!) helpers provided by this addon are simply wrappers:

- https://github.com/oskarrough/ember-date-fns/blob/master/addon/helpers/date-format.js
- https://github.com/oskarrough/ember-date-fns/blob/master/addon/helpers/date-from-now.js

That being said, I still think there's value in getting date-fns + a few useful helpers with one command `ember install ember-date-fns`.

I really appreciate all the work @btecu did to make this work with webpack (before ember-auto-import was common), but maybe it is time to remove it and let the addon install ember-auto-import + date-fns directly in the consuming app.

What do you guys think?

**Comment by RobbieTheWagner** [comment]
The main thing I'd like is to get tree shaking support. How we do that, doesn't matter much to me.

**Comment by btecu** [comment]
@oskarrough I don't believe it was me who added `webpack` support.

**Comment by oskarrough** [comment]
Right sorry, I meant  @n1ru4l :)

**Comment by btecu** [comment]
@rwwagner90 @oskarrough @robclancy @amk221 Can any of you try #15?
