### ISSUE TITLE
ember-browserify is required for this to work.

### ISSUE THREAD

**Issue by ShogunPanda** [oskarrough/ember-date-fns#4]
Hi!
I tried on my app where I didn't have `ember-browserify` included and it failed when importing `npm:date-fns/format`.

I solved by embedding `ember-browserify` in my package.json, so apparently that is a required dependency.
Thanks!

**Comment by oskarrough** [comment]
Thanks. I'll add it to the installation instructions.

Would be great if it wasn't necessary to explicitly install it though...

**Comment by oskarrough** [comment]
Fixed by https://github.com/oskarrough/ember-date-fns/commit/052f506a8bd1f58be6b4fc2a6f8079dbf999107b
