### ISSUE TITLE
Will this reduce app file size? 

### ISSUE THREAD

**Issue by MartinMalinda** [oskarrough/ember-date-fns#6]
This comment: https://github.com/date-fns/date-fns/issues/275#issuecomment-264941412
states that moment.js and date-fns have similar bundle size. Date-fns win in files only if you can import just the code you need. 
I am not sure if ember-browserify includes only the imported pieces of code or if it ships the whole npm package dist file.

**Comment by MartinMalinda** [comment]
It seems like browserify should include only the relevant parts. https://github.com/date-fns/date-fns/issues/275#issuecomment-265100911

But it would be great to verify this.

**Comment by oskarrough** [comment]
Let me just take a _moment_... :trollface: 

No, you're right. Here's my small non-scientific comparison. I took the current state of the dummy app in this repo and ran `ember build`. This is the total size of the `dist` folder. 

- 5828 kb (two date-fns helpers)
- 6076 kb (ember-moment)

So in this case I'd save 242 kb.

Disclaimer: I use ember-moment in many projects and can only recommend it.

**Comment by oskarrough** [comment]
Here's another try with `ember build -p` and `ember build`, respectively. I deleted everything in `dist` expect the .css and .js in `dist/assets`.

```
660   date-fns-minified
720   moment-minified

+60kb

2344  date-fns
2448  moment

+144kb
```

**Comment by MartinMalinda** [comment]
Cool! I tried the same thing now (build size comparison).
JS assets size: (gzip)
277kb - no moment, no date-fns
280kb - date-fns
293kb - ember-moment

Great! Thanks for the addon.

**Comment by oskarrough** [comment]
Glad you could use it! I updated the readme. If it's ~15-60kb you save it's perhaps not worth mentioning.

**Comment by MartinMalinda** [comment]
@oskarrough Just re-checked this recently and noticed that ember-moment also adds ember-cli-moment-shim to package json, which is what kept my build output high *facepalm*. With ember-cli-moment-shim removed the difference is way bigger.
