### ISSUE TITLE
how to import format into a controller

### ISSUE THREAD

**Issue by supersabillon** [oskarrough/ember-date-fns#7]
Thanks for providing the format helper, is there a better way to import the format function to a controller or should I do the same line you have in the dummy app: `import format from 'npm:date-fns/format';`?

**Comment by oskarrough** [comment]
If you want the `format` function from date-fns I would do exactly as you suggest, using ember-browserify.

**Comment by oskarrough** [comment]
Closing. Feel free to reopen if there's anything.
