### ISSUE TITLE
Get rid of ember-browserify dependency

### ISSUE THREAD

**Issue by oskarrough** [oskarrough/ember-date-fns#8]
Would be nice you didn't have to install ember-browserify to use this addon. But it's the easiest way I have found to follow the date-fns documentation on importing each function:

```
import closestIndexTo from 'date-fns/closest_index_to'
```

… but we can't import directly from node_modules with ember-cli. What to do?

Inspiration:

- https://github.com/asakusuma/ember-rollup
- https://github.com/mike-north/ember-lodash

**Comment by n1ru4l** [comment]
@oskarrough Ember Apollo Client uses a WebpackDependencyPlugin

https://github.com/bgentry/ember-apollo-client/blob/master/lib/webpack-dependency-plugin.js
https://github.com/bgentry/ember-apollo-client/blob/e2d8df6103ecf883d8385bd0504f85a89c6c0d86/index.js

**Comment by n1ru4l** [comment]
Resolved in #10
